### ISSUE TITLE
Doing a wheel build and install of `datanommer-commands` installs the `tests/` directory for some reason

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/datanommer#1036]
This is weird and I can't figure out why it is, but doing a standard package install of datanommer-commands:

    %build
    %pyproject_wheel

    %install
    %pyproject_install
    %pyproject_save_files datanommer

results in the `tests/` directory being installed. The `pyproject-modules` file written out by `%pyproject_save_files` also lists it:

    <mock-chroot> sh-5.1# cat /builddir/build/BUILD/datanommer-commands-1.0.3-2.fc38.x86_64-pyproject-modules 
    datanommer
    datanommer.commands
    tests
    tests.conftest
    tests.test_commands

though again I've no idea why. The `pyproject-files` file does not include any files from it, even though the files were installed.

I don't see any reason why this is happening. It does not happen with the very similar `datanommer.models` module (packaged as `python-datanommer-models`). That spec file works just the same, and the `pyproject.toml` is very similar, but in that case `tests/` doesn't get installed.

**Comment by AdamWill** [comment]
Oh, it also installs `tox.ini`.

**Comment by hroncok** [comment]
> The pyproject-files file does not include any files from it, even though the files were installed.

That is by usage. pyproject-files is created by `%pyproject_save_files` and you gave it one positional argument: `datanommer` -- which means "list all files from the top-level datanommer module" (which does not include the files from the top-level tests module).

**Comment by hroncok** [comment]
Is this before or after 62c6d7a418050b59a1b2322bbbeb5e4190e9302c was included?

**Comment by AdamWill** [comment]
@hroncok but `pyproject-modules` is written out by the *same* `%pyproject_save_files` command, and that one *does* include the `tests` modules. That doesn't seem consistent.

> Is this before or after https://github.com/fedora-infra/datanommer/commit/62c6d7a418050b59a1b2322bbbeb5e4190e9302c was included?

Doh, that's a good point. I'd been just looking at the develop branch and kinda assuming the 1.0.4 tarball had that change, but of course maybe not...

...

ah, yeah, of course that's it. We have 1.0.3 in dist-git and that tarball has the old, bad form of `pyproject.toml`. That'd certainly explain it. I'll check that, but it's almost certainly the reason. Thanks for spotting the obvious :D

**Comment by hroncok** [comment]
Yeah, it is indeed not consistent. Will chcek why the extra modules are saved.

**Comment by hroncok** [comment]
> Yeah, it is indeed not consistent. Will chcek why the extra modules are saved.

https://bugzilla.redhat.com/show_bug.cgi?id=2127958
