### ISSUE TITLE
fedmsg.com domain is expired

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/datanommer#111]
fedmsg.com now shows this page.

![image](https://user-images.githubusercontent.com/8781107/48002907-f70e2280-e11d-11e8-9ebe-890d699f5998.png)

---
It is either expired, or hijacked, or both.

**Comment by ralphbean** [comment]
Doh.

@puiterwijk, @lmacken - I have a memory that you guys did some transfer of this (or was that another domain?)

**Comment by abitrolly** [comment]
https://whois.icann.org/en/lookup?name=fedmsg.com shows that @lmacken owns it, but we gonna lose it in 2 days unless you have an emergency number to contact Luke.

**Comment by abitrolly** [comment]
Now it shows Database Error.

![image](https://user-images.githubusercontent.com/8781107/136096953-98d24010-4884-4fbb-81ed-2e621591a00f.png)
