### ISSUE TITLE
Unable to filter buildsys messages by user 

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/datanommer#1257]
Maybe I'm missing something, but I'm not able to apply a `user` filter to koji messages.
At first I thought datagrepper was not taking into account Koji messages, as quering by user will not show anything:
https://apps.fedoraproject.org/datagrepper/raw/?user=mattia

But then I've found that messages are there:
https://apps.fedoraproject.org/datagrepper/raw/?category=buildsys

Just the `category=buildsys` and `user` filter doesn't work well when applying both:
https://apps.fedoraproject.org/datagrepper/raw/?category=buildsys&user=mattia

**Comment by novicejava1** [comment]
Hi @mattiaverga,

I think you are missing the timestamp argument (ie. start, end or delta) that need to be passed to the request. I tried the following and it provides with a response. But i dont get any message using the buildsys category during that timeframe.

From browser
```
https://apps.fedoraproject.org/datagrepper/v2/search?start=2023-06-01T01:00:00+00:00&end=2023-06-21T23:11:40+00:00&category=bodhi&user=mattia
```
From CLI
```
$ http get https://apps.fedoraproject.org/datagrepper/v2/search start==2023-06-01T01:00:00+00:00 end==2023-06-21T23:11:40+00:00 category==bodhi user==mattia | jq
```

**Comment by abompard** [comment]
Correct, our datanommer instance does not have the koji message schemas installed, and as a result it's unable to extract the user associated with the build from the incoming message. I'll fix that (and move the issue to datanommer).
