### ISSUE TITLE
How to store messages in the datanommer db?

### ISSUE THREAD

**Issue by abompard** [fedora-infra/datanommer#128]
Currently, messages (both when sent via fedmsg or fedora-messages) are stored in the datanommer db in the fedmsg format (e.g. https://apps.fedoraproject.org/datagrepper/id?id=2021-01b823ed-6b7c-480c-a4a4-4af0670692ef&is_raw=true&size=extra-large) however, this is not the native fedora-messaging format.

After we convert datanommer to fedora-messaging, do we:

* store messages from that point in the fedora-messaging format, but leave all the old ones in the old format?
* convert all the old messages to the fedora-messaging format?
* convert all new messages to the fedmsg format and keep doing that for all time.

**Comment by ryanlerch** [comment]
Please correct me on this, but i think the plan is going to be:

* after deploying the new version of datanommer, that is consuming from fedora-messaging, all the messages from that point on will be stored in the format on that side of the bridge.
* all the old messages will stay in the fedmsg side in the db
* datagrepper will, by default return the messages in the new format -- converting the old messages to the new format when returning results. (API BREAKING).
* datagrepper will also now supply a legacy endpoint that returns all messages in the old format.

**Comment by abompard** [comment]
It's probably a better idea to have the current endpoint deliver the old format and have a new endpoint for the new format, as it is a priority not to break the API.
There are currently two main endpoints: `/raw` and `/id`. Let's create a `/v2/search` and a `/v2/id` endpoint for the new format.

**Comment by ryanlerch** [comment]
So really, the only work items here are to create the new v2 endpoints?

The actual storing of the messages in the fedora-messaging format is kind of inherit to changing the consumer to fedora-messaging, right

**Comment by abompard** [comment]
Yeah we'll store the `message.body` dict of the fedora-messaging message in the `msg` column. Datagrepper will have to be adjusted to handle messages in the old format and in the new format.
