### ISSUE TITLE
Check timescaledb is in Fedora / EPEL

### ISSUE THREAD

**Issue by abompard** [fedora-infra/datanommer#131]
if not package it

##### Update 1

timescaledb is packaged for fedora: https://src.fedoraproject.org/rpms/timescaledb

##### https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/rhel-centos/installation-yum/#yum-installation

**Comment by LenkaSeg** [comment]
timescaledb not found in EPEL

Testing of timescaledb in Centos8: successful

Tested in a podman container:

`podman run -it docker.io/centos:8`

Following the guide: https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/rhel-centos/installation-yum/#yum-installation

**Comment by LenkaSeg** [comment]
Notes:

I ran into a problem with this command `timescaledb-tune`, it is solved here:

https://github.com/timescale/timescaledb-tune/issues/46

`timescaledb-tune --pg-config=/usr/pgsql-13/bin/pg_config`

`su postgres`

Good instructions found here: 
`cat /usr/lib/systemd/system/postgresql-13.service`

First run initdb:

Use "/usr/pgsql-13/bin/postgresql-13-setup initdb" to initialize the database cluster.

Start the postgres database with:

`/usr/pgsql-13/bin/postmaster -D /var/lib/pgsql/13/data/`

From another terminal window, inside the centos8 container:

`psql -U postgres`

Create a table following this [guide](https://docs.timescale.com/timescaledb/latest/getting-started/create-hypertable/#chunks-and-hypertables)

`CREATE TABLE IF NOT EXISTS ...`

`SELECT create_hypertable('weather_metrics', 'time');`
output: `ERROR:  function create_hypertable(unknown, unknown) does not exist`

Seems that timescaledb is not there.
Run:

`select * from pg_extension;`

output:
  oid  | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-------+---------+----------+--------------+----------------+------------+-----------+--------------
 13420 | plpgsql |       10 |           11 | f              | 1.0        |           | 
(1 row)

Timescale is really not there.

Run:
`create extension if not exists timescaledb cascade;`

output:
WELCOME TO
 TIMESCALEDB
               Running version 2.3.1

Timescale is there!

Confirm with `select * from pg_extension;`

Create hypertable:
`SELECT create_hypertable('weather_metrics','time');`

output: 

```
       create_hypertable       
------------------------------
 (1,public,weather_metrics,t)
(1 row)```

**Comment by abompard** [comment]
OK, so you confirm that upstream's yum repo works on CentOS8. Cool, thanks.
