### ISSUE TITLE
Convert datanommer.models to store fedora-messaging style messages

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/datanommer#133]
Currently, datanommer.models store messages in the database in fedmsg format. Also the metadata (dates, topics, etc) that it stores as additional fields is extracted from the fedmsg style message.

When we implement #132 the messages that we add to the database via the model add() function will need to be properly handled in that function/

Note to that this issue is dependant on the outcome of the #128 spike ticket

**Comment by ryanlerch** [comment]
I *think* this is pretty much covered by #161 and #155 

is there any more to do on this one?

**Comment by abompard** [comment]
No, I think that's it, thanks!
