### ISSUE TITLE
Clean out codebase

### ISSUE THREAD

**Issue by abompard** [fedora-infra/datanommer#134]
There is a bunch of tools and other stuff that we should decide if we want to keep in the codebase, or just remove and stop supporting it. (add more to this list if needed)

- [x] https://github.com/fedora-infra/datanommer/tree/develop/tools -- some of this stuff may be useful, but probably suited for another repo. maybe
- [x] https://github.com/fedora-infra/datanommer/tree/develop/datanommer.commands

**Comment by ryanlerch** [comment]
Will probably leave datanommer.commands, as its already ported to fedora-messaging and works fine

**Comment by ryanlerch** [comment]
as for the other things that are in /tools here is what doesnt really apply anymore:

* https://github.com/fedora-infra/datanommer/tree/develop/tools/first-week-of-datanommer
* https://github.com/fedora-infra/datanommer/tree/develop/tools/gource
* https://github.com/fedora-infra/datanommer/blob/develop/tools/active-contrib.py

these all appear to be small tools and scripts for pulling data and statistics out of the datanommer database.

THinking i might move these to a new datanommer-tools repo, and then archive it, and then remove them from the main datanommer repo.

**Comment by ryanlerch** [comment]
scratch that -- going to remove these three scripts from the codebase.
