### ISSUE TITLE
Port to Openshift

### ISSUE THREAD

**Issue by abompard** [fedora-infra/datanommer#135]

**Comment by LenkaSeg** [comment]
Check how it is done in noggin.
Noggin uses s2i build.

DN and DG will be 1 project 1 pod for each
PG on separate VM
DG - 1 route, 1 service
- prepare ansible roles

Defining resources:
deploymentconfig.yml, buildconfig.yml, services.yml for timescaledb and the web

Figure out how to test it in stg.
In the meantime:
Downloading codeready containers (CRC) to test the build locally and use the oc.

**Comment by LenkaSeg** [comment]
Draft PR on ansible here:

https://pagure.io/fedora-infra/ansible/pull-request/731
