### ISSUE TITLE
Add "source" column in data table

### ISSUE THREAD

**Issue by iliana** [fedora-infra/datanommer#20]
A "source" column needs to be added to the data table.

Data put in the table from datanommer should have that field set to "datanommer"; this is so we can see what put in what data (older data would be put in with a script, for example).

**Comment by ralphbean** [comment]
Cool.  We can still do this.  It will need an alembic upgrade script to add the column and provide a good default for old rows.

**Comment by iliana** [comment]
Oh hey this is done (#50)
