### ISSUE TITLE
Make fedbadges use the new datanommer.models

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/datanommer#209]

**Comment by StephenCoady** [comment]
Unassigning this for now as it makes sense to start with fmn. Mostly because its very difficult to test badges.

**Comment by ryanlerch** [comment]
This is now done, and working in staging. 

the branch python2 branch here in datanommer contains the code, and we hotfix badges with it via andible.

the follwoing PR is to be run after we deploy datanommer:

https://pagure.io/fedora-infra/ansible/pull-request/791
