### ISSUE TITLE
the 'contains' parameter in datanommer.models Message.grep() function is broken 

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/datanommer#231]
The issue is with:

https://github.com/fedora-infra/datanommer/blob/develop/datanommer.models/datanommer/models/__init__.py#L395

```
        if contains:
            query = query.filter(
                or_(*(Message._msg.like("%%%s%%" % contain) for contain in contains))
            )
```

_msg was previously just a string of the json message, but now it is called "msg" and is JSONB -- so the .like doesnt work anymore either

**Comment by ryanlerch** [comment]
any idea on how to search the JSONB for a substring? 

did some digging, but not much worked -- any thoughts or pointers?

**Comment by abompard** [comment]
Here's a couple of pointers:
- Reference: https://www.postgresql.org/docs/9.4/functions-json.html
- A few examples: https://medium.com/hackernoon/how-to-query-jsonb-beginner-sheet-cheat-4da3aa5082a3

The `json_extract_path_text` (or the `#>>` operator) seem promising.
