### ISSUE TITLE
Update FMN to not use datanommer

### ISSUE THREAD

**Issue by StephenCoady** [fedora-infra/datanommer#232]

**Comment by StephenCoady** [comment]
I've got a few pull requests which we'll need to test that should make this possible.

https://github.com/fedora-infra/fmn/pull/324
https://github.com/fedora-infra/fmn/pull/323
https://pagure.io/fedora-infra/ansible/pull-request/779

Once they have been reviewed I can deploy on `notifs-backend02` to test that everything works. Once it does I can hotfix the changes to `notifs-backend01`

**Comment by StephenCoady** [comment]
So all of my changes seem to be OK but as we are in a freeze at the moment and notifs-backend02 is in the frozen inventory group I can't really test these changes. Hence moving it to blocked. I've gotten the patch ready to test in ansible and if everything goes OK I will rebuild python3-fmn for our infra.

**Comment by abompard** [comment]
Closing since the new FMN does not use datanommer directly
