### ISSUE TITLE
Add a uuid field to the models

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/datanommer#49]
And an alembic upgrade script that assigns every message that doesn't have a uuid with a random one.

Then, add a classmethod to `Message` that allows us to query for a unique message.

Then, add an extra `uuid` option to the `grep` classmethod.

**Comment by iliana** [comment]
Old messages will not be given a UUID in order to keep their signatures valid. Giving every previous message a UUID is unnecessary. (#fedora-apps, 02:08 UTC 2013 Sep 5)

**Comment by iliana** [comment]
#62
