### ISSUE TITLE
do not enable datanommer by default

### ISSUE THREAD

**Issue by tyll** [fedora-infra/datanommer#54]
After installing datanommer on F19, it is enabled by default in /etc/fedmsg.d/datanommer.py and run when I start fedmsg-hub. This is unexpected as it needs configuration and is insecure by default.

**Comment by ralphbean** [comment]
This should be fixed in the rpm spec now -- http://pkgs.fedoraproject.org/cgit/python-datanommer-models.git/commit/?id=6e34d1afd6e6bed8ca6e00036e78668292230889

Can you confirm?
