### ISSUE TITLE
insecure temp database

### ISSUE THREAD

**Issue by tyll** [fedora-infra/datanommer#55]
datanommer uses /tmp/datanommer.db as default database and is enabled by default in Fedora 19. This might lead to security problems.

**Comment by ralphbean** [comment]
Any idea what alternative we should use?

We could use postgres by default... too heavyweight.

Disable datanommer by default.. ?

Use a more secure location for the default sqlite db?  Any recommendations on where that should be?

**Comment by tyll** [comment]
It should be disabled by default and a good default location would be /var/lib/datanommer/datanommer.sqlite or similar.

**Comment by tyll** [comment]
Since the current solution will be cleared is not persistent and will be removed on reboot, the in memory database might be a different option. Or datanommer could just refuse to start unless database was specified.

**Comment by tyll** [comment]
btw. it also seems that datanommer will not even run out of the box, because there were tracebacks in the fedmsg-hub output when I accidently started it.

**Comment by ralphbean** [comment]
Ah, can you file another issue with those tracebacks?

**Comment by ralphbean** [comment]
@tyll, can you comment on #57 and confirm that that will do the trick?

**Comment by ralphbean** [comment]
Here's an equivalent patch for rawhide - http://pkgs.fedoraproject.org/cgit/python-datanommer-models.git/commit/?id=6e34d1afd6e6bed8ca6e00036e78668292230889
