### ISSUE TITLE
datanommer-dump should print out valid JSON

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/datanommer#6]
Currently, each individual message that it prints out is valid json, but the whole output is not a valid json blob.

The test of this would be if you could do the following at the shell:

```
datanommer-dump > myfile.json
```

and then do the following in Python:

``` python
import json
with open("myfile.json") as f:
    my_object = json.loads(f.read())
```

**Comment by HousewifeHacker** [comment]
this is completed

**Comment by ralphbean** [comment]
As of ad37c20fe80786bac7329b7ffd48db1b1c2c644a and 4485519b93eef803e07801d4bb3a778ba758ed2b.  Nice work!
