### ISSUE TITLE
Database timestamps are stored using the local timezone

### ISSUE THREAD

**Issue by olasd** [fedora-infra/datanommer#73]
Hi folks,

datanommer seems to store the messages using the local timezone instead of UTC. That looks wrong to me, but maybe there's a reason.

I can come up with a patch if you'd like. Depending on the deployment, there might be a need for a migration too.

Cheers,
Nicolas

**Comment by ralphbean** [comment]
If that's the case then it is wrong.  It should store using UTC :(  Patch appreciated.

The tz on the server fedora has running is UTC, so that dataset should be fine.

**Comment by ralphbean** [comment]
Closed with #74.
