### ISSUE TITLE
Latest tags are missing

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/datanommer#88]
The Fedora package [appears to be for 0.7.0](http://pkgs.fedoraproject.org/cgit/rpms/python-datanommer-models.git/tree/python-datanommer-models.spec), but there is no sign of that tag or release here, nor any of the 0.6.x series.

**Comment by ralphbean** [comment]
See [pypi](https://pypi.python.org/pypi/datanommer.models)?

**Comment by QuLogic** [comment]
This ticket is about the _tags_, i.e., the exact originating commit. Finding a tarball is not the problem.

**Comment by QuLogic** [comment]
Now PyPI is at 0.9.1, and there are _still_ no new tags in this repo, so I don't know why this was closed.
